---
all:
  vars:
    ansible_port: 22
    project_name: vps
    project_state: vps
  children:
    # Hosting location
    nodes:
      hosts:
        vps_test1:
          ansible_host: 91.149.240.129
          server_name: VPS_TEST1
        vps_test2:
          ansible_host: 45.140.169.83
          server_name: VPS_TEST2
        vps_test3:
          ansible_host: 45.140.169.84
          server_name: VPS_TEST3

    #Test
    test:
      hosts:
        vps_test1:
        vps_test2:
        vps_test3:
